[tool.poetry]
name = "ingestion_worker"
version = "0.1.0"
description = "Aura Ingestion Worker Service"
authors = ["Mohammad Atashi"]

[tool.poetry.dependencies]
python = ">=3.11, <3.13"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


