apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aura-platform.fullname" . }}-api-gateway
  namespace: {{ .Values.global.namespace | default "aura-platform" }}
  labels:
    app.kubernetes.io/name: {{ include "aura-platform.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: api-gateway
spec:
  replicas: {{ .Values.apiGateway.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "aura-platform.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: api-gateway
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "aura-platform.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/component: api-gateway
    spec:
      serviceAccountName: {{ include "aura-platform.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      containers:
        - name: api-gateway
          image: "{{ .Values.apiGateway.image.repository }}:{{ .Values.apiGateway.image.tag }}"
          imagePullPolicy: {{ .Values.apiGateway.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "aura-platform.fullname" . }}-config
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "aura-platform.fullname" . }}-config
                  key: POSTGRES_PORT
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: {{ include "aura-platform.fullname" . }}-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ include "aura-platform.fullname" . }}-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "aura-platform.fullname" . }}-secrets
                  key: POSTGRES_PASSWORD
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "aura-platform.fullname" . }}-config
                  key: RABBITMQ_HOST
            - name: RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "aura-platform.fullname" . }}-config
                  key: RABBITMQ_PORT
            - name: RABBITMQ_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ include "aura-platform.fullname" . }}-config
                  key: RABBITMQ_USER
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "aura-platform.fullname" . }}-secrets
                  key: RABBITMQ_PASSWORD
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "aura-platform.fullname" . }}-secrets
                  key: SECRET_KEY
            - name: INSTAGRAM_APP_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "aura-platform.fullname" . }}-secrets
                  key: INSTAGRAM_APP_ID
            - name: INSTAGRAM_APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "aura-platform.fullname" . }}-secrets
                  key: INSTAGRAM_APP_SECRET
            - name: INSTAGRAM_WEBHOOK_VERIFY_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "aura-platform.fullname" . }}-secrets
                  key: INSTAGRAM_WEBHOOK_VERIFY_TOKEN
          livenessProbe:
            {{- toYaml .Values.apiGateway.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.apiGateway.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.apiGateway.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
            capabilities:
              drop:
                - ALL
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aura-platform.fullname" . }}-api-gateway
  namespace: {{ .Values.global.namespace | default "aura-platform" }}
  labels:
    app.kubernetes.io/name: {{ include "aura-platform.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: api-gateway
spec:
  type: {{ .Values.apiGateway.service.type }}
  ports:
    - port: {{ .Values.apiGateway.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "aura-platform.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: api-gateway
