apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace | default "aura-platform" }}
  labels:
    name: {{ .Values.global.namespace | default "aura-platform" }}
    app.kubernetes.io/name: {{ include "aura-platform.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
