apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aura-platform.serviceAccountName" . }}
  namespace: {{ .Values.global.namespace | default "aura-platform" }}
  labels:
    app.kubernetes.io/name: {{ include "aura-platform.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
